name: Test On Chrome Browser
on: push
jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
         cache-dependency-path: 'package-lock.json'
         working-directory: client
         command: npm run test:browser